default: &default
  elastic_timeout: 5

test:
  <<: *default
  host: <%= ENV["ES_HOST"] || "http://localhost:9200" %>

development:
  <<: *default
  host: <%= ENV["ES_HOST"] || "http://localhost:9200" %>
  verify_ssl: false

integration:
  <<: *default
  host: <%= ENV["ES_HOST"] %>

staging:
  <<: *default
  host: <%= ENV["ES_HOST"] %>
  vcap_services: '<%= ENV["VCAP_SERVICES"] %>'

production:
  <<: *default
  host: <%= ENV["ES_HOST"] %>
  vcap_services: '<%= ENV["VCAP_SERVICES"] %>'
